### PR TITLE
Roll Engine: Provide errors if user list rolls an empty array

### LINKED ISSUE #136: Roll Engine: Provide errors if user list rolls an empty array
Currently the roll engine handles empty array by returning empty strings (examples below).
`5l[]` -> `, , , ,` 
`5ul[]` -> `, , , ,`

An early out error message would be more intuitive for users and allow us to skip some computation.

### PR DESCRIPTION
**Pull request by SillySalamndr**
Fixes #136

Summary
-------
(Include a summary of the work done or the reasoning for the pivot here)

Local Tests Performed
---------------------
- [X] bot still turns on

Issue
-----
Closes #136

### CODE REVIEW

**Review by ntseng — CHANGES_REQUESTED** [review]
All `/roll` now crash HorizonsBot.

**Comment by SillySalamndr** [comment]
Well, it is worse on my end; my test bot won't even connect to Discord right now. It's gonna take a bit of time for me to address this.

**Review by ntseng — APPROVED** [review]

**Comment by SillySalamndr** [comment]
...It really was that simple, wasn't it?

**Comment by ntseng** [comment]
Error messages from a working setup helped :P

**Pull request merged**
